ERROR - 2023-10-02 00:03:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sfoe4134_satriam'@'localhost' (using password: YES) in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'sfoe4134_satria...', Object(SensitiveParameterValue), 'sfoe4134_HSEAPP', 3306, '', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\APIclubhouse\app\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Login->index()
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\APIclubhouse\app\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Login->index()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-10-02 00:03:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
OR `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
ERROR - 2023-10-02 00:03:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sfoe4134_satriam'@'localhost' (using password: YES) in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'sfoe4134_satria...', Object(SensitiveParameterValue), 'sfoe4134_HSEAPP', 3306, '', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\APIclubhouse\app\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Login->index()
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\APIclubhouse\app\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Login->index()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-10-02 00:03:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
OR `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
ERROR - 2023-10-02 01:42:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sfoe4134_satriam'@'localhost' (using password: YES) in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'sfoe4134_satria...', Object(SensitiveParameterValue), 'sfoe4134_HSEAPP', 3306, '', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\APIclubhouse\app\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Login->index()
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\APIclubhouse\app\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Login->index()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-10-02 01:42:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
OR `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(34): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
CRITICAL - 2023-10-02 02:34:18 --> Token Required
in APPPATH\Controllers\Hauling.php on line 212.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Hauling->tampil()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Hauling))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
ERROR - 2023-10-02 02:39:13 --> mysqli_sql_exception: Table 'db_she.roles' doesn't exist in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT `users`....', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\app\Models\UserModel.php(76): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\APIclubhouse\app\Controllers\Auth.php(34): App\Models\UserModel->tampilsemuadata()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth->indexall()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-10-02 02:39:13 --> Call to a member function getResult() on bool
in APPPATH\Models\UserModel.php on line 76.
 1 APPPATH\Controllers\Auth.php(34): App\Models\UserModel->tampilsemuadata()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->indexall()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
CRITICAL - 2023-10-02 02:39:16 --> Signature verification failed
in VENDORPATH\firebase\php-jwt\src\JWT.php on line 136.
 1 APPPATH\Controllers\Me.php(27): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTU5NTM3OTQsImV4cCI6MTY5NTk2MDk5NCwidWlkIjoiMSIsImVtYWlsIjoic2F0cmlhQHJlaGFuZGxpbmcuY29tIiwicm9sZSI6InVzZXIiLCJuYW1hIjoiU2F0cmlhIE11bHlhIEFkaXdhcmRhbmEifQ.SQu4VC7Uidzf9V4KJxjTRdQ7JBnECq1uOXIRzehiyMI', 'satriaahahaha', [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Me->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Me))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
CRITICAL - 2023-10-02 02:40:18 --> Signature verification failed
in VENDORPATH\firebase\php-jwt\src\JWT.php on line 136.
 1 APPPATH\Controllers\Me.php(27): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTU5NTM3OTQsImV4cCI6MTY5NTk2MDk5NCwidWlkIjoiMSIsImVtYWlsIjoic2F0cmlhQHJlaGFuZGxpbmcuY29tIiwicm9sZSI6InVzZXIiLCJuYW1hIjoiU2F0cmlhIE11bHlhIEFkaXdhcmRhbmEifQ.SQu4VC7Uidzf9V4KJxjTRdQ7JBnECq1uOXIRzehiyMI', 'satriaahahaha', [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Me->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Me))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
CRITICAL - 2023-10-02 02:54:31 --> Call to a member function orderBy() on null
in APPPATH\Controllers\Pengaduan.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pengaduan->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
CRITICAL - 2023-10-02 02:54:54 --> Call to a member function orderBy() on null
in APPPATH\Controllers\Pengaduan.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pengaduan->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
ERROR - 2023-10-02 02:56:31 --> mysqli_sql_exception: Unknown column 'id_pengaduans' in 'order clause' in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\APIclubhouse\app\Controllers\Pengaduan.php(16): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Pengaduan->index()
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-02 02:56:31 --> Unknown column 'id_pengaduans' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC', [], false)
 5 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Pengaduan.php(16): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pengaduan->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
ERROR - 2023-10-02 02:59:25 --> mysqli_sql_exception: Table 'db_she.pengaduan' doesn't exist in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\app\Controllers\Pengaduan.php(81): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Pengaduan->create()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2023-10-02 03:05:37 --> mysqli_sql_exception: Table 'db_she.pengaduan' doesn't exist in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\app\Controllers\Pengaduan.php(73): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Pengaduan->create()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2023-10-02 03:05:54 --> mysqli_sql_exception: Unknown column 'nama_lokasi' in 'field list' in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\app\Controllers\Pengaduan.php(73): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Pengaduan->create()
#6 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2023-10-02 03:13:59 --> mysqli_sql_exception: Unknown column 'id_pengaduans' in 'order clause' in C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\APIclubhouse\app\Controllers\Pengaduan.php(16): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Pengaduan->index()
#8 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#9 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-10-02 03:13:59 --> Unknown column 'id_pengaduans' in 'order clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pengaduans`
ORDER BY `id_pengaduans` ASC', [], false)
 5 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Pengaduan.php(16): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pengaduan->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
CRITICAL - 2023-10-02 03:19:08 --> unlink(C:\xampp\htdocs\APIclubhouse\public/pengaduan/1696234296.JPG): No such file or directory
in APPPATH\Controllers\Pengaduan.php on line 108.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'unlink(C:\\xampp\\htdocs\\APIclubhouse\\public/pengaduan/1696234296.JPG): No such file or directory', 'C:\\xampp\\htdocs\\APIclubhouse\\app\\Controllers\\Pengaduan.php', 108)
 2 APPPATH\Controllers\Pengaduan.php(108): unlink('C:\\xampp\\htdocs\\APIclubhouse\\public/pengaduan/1696234296.JPG')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pengaduan->delete('4')
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\APIclubhouse\\public\\index.php')
